# site settings
title: SynBioSoc
subtitle: Cambridge University Synthetic Biology Society
email: cusbs-executive@srcf.net
description: The Synthetic Biology Society aims to promote the field of synthetic biology (SynBio) amongst the student community and within schools in Cambridge. Particular focus will be given to its real-world applications and interdisciplinary nature. Expert speakers from different SynBio disciplines will be invited to give talks, and links to external SynBio events and networks will be developed. We aim to work closely with both the SynBio SRI and the Open Plant initiative, and strengthen their direct links with STEM students.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Engineering Dept, Trumpington St, Cambridge CB2 1PZ
city: Cambridge
state: Cambridgeshire
zip_code: CB2 1PZ
country: UK
#phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/cusynbiosoc
github_url:
gitlab_url: https://github.com/cusynbiosoc
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/CU_SynBioSoc

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman